name: Submit new Provider Signing Key
description: Submit a new OpenTofu Provider Signing Key
title: "Provider Key: "
labels: ["provider-key", "submission"]
body:
  - type: input
    id: namespace
    attributes:
      label: Provider Namespace
      description: GitHub Username or Organization that contains Providers
    validations:
      required: true
  - type: input
    id: providername
    attributes:
      label: Provider Name (Optional)
      description: Name of the provider this key is used for (without the terraform-provider- prefix). If omitted, this key will be added at the namespace/organization level.
    validations:
      required: false
  - type: checkboxes
    id: public_membership
    attributes:
      label: Public Membership
      description: >-
        **Required:** If this is for a GitHub organization, your membership in that organization **must** be public.
        This submission will fail automated validation if your membership is not publicly visible.
        [How to make your membership public](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership).
        If you are unable to make your membership public, please [open a different issue](https://github.com/opentofu/registry/issues/new) to contact the OpenTofu team for assistance.
      options:
        - label: I have made my membership public
          required: true
  - type: textarea
    id: gpgkey
    attributes:
      label: Provider GPG Key
      description: Armoured public PGP key
